### ISSUE TITLE
Northern Ireland data

### ISSUE THREAD

**Issue by alexnorton** [martinjc/UK-GeoJSON#1]
It'd be great if some data for Northern Ireland was added to the repo, maybe starting with WPCs?

**Comment by martinjc** [comment]
Yeah, I'd love to add NI data. Unfortunately it does not seem to be as clearly open as data from the rest of the UK. Boundary data for NI is available from http://www.gistrategyni.gov.uk/index.htm, and the licence *seems* to say derived works can be redistributed, but I need to get into it further before I'd feel sure I can transform the data to geojson and republish it

**Comment by alexnorton** [comment]
Cheers for the reply!

**Comment by 24ma13wg** [comment]
Northern Ireland would be great! My need is for the Westminster parliamentary constituencies: http://en.wikipedia.org/wiki/List_of_parliamentary_constituencies_in_Northern_Ireland. Cheers.

**Comment by chris48s** [comment]
Northern Ireland vector boundaries are available under an Open Government Licence

http://www.nidirect.gov.uk/osni-open-data

http://osni.spatial-ni.opendata.arcgis.com/datasets?q=Boundaries&sort_by=relevance

**Comment by martinjc** [comment]
That's great news. I'll add it to the todo list to get NI boundaries added. Unless anyone wants to submit a PR?

**Comment by martinjc** [comment]
NI boundaries for wards, parliamentary constituencies, local government districts and county boundaries now added. Will update web page now.
