### ISSUE TITLE
OSGB_Grid_1km

### ISSUE THREAD

**Issue by mistatoms** [martinjc/UK-GeoJSON#11]
I have been trying to convert the OSGB_1km grid into a json file which powerBI can read.

When uploading the following files...
https://github.com/charlesroper/OSGB_Grids/blob/master/Shapefile/OSGB_Grid_1km.shp
https://github.com/charlesroper/OSGB_Grids/blob/master/Shapefile/OSGB_Grid_1km.dbf
https://github.com/charlesroper/OSGB_Grids/blob/master/Shapefile/OSGB_Grid_1km.prj

...to mapshaper it is all looking good...
![ms](https://cloud.githubusercontent.com/assets/26797281/24515098/71fd0650-156e-11e7-9700-cc281988fffb.jpg)

...SHP and DBP combine nicely with PLAN_NO acting as key for shape attribute.

When exporting to GEOjson or TOPjson I don't manage to create a file which powerBI can process.
When using a json file in powerBI from your website, everything works just perfectly well.
What magic formula do you have to create json files which work in powerBI?

**Comment by martinjc** [comment]
I wish I could tell you - but not knowing what mapshaper does on export, it's hard to know what's different.

I can tell you that my process is pretty much the same (give or take) as Mike Bostock's in his "[Let's make a map](https://bost.ocks.org/mike/map/)" post, although even that has now been [superseded](https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c).

Hopefully the solution you seek is somewhere there...
